=== Rahwulkumar/MCA_LAB-7-Z-/projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:element name="projects">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="project" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="image" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rahwulkumar/MCA_LAB-7-Z-/projects.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="projects.xsl"?>

<projects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projects.xsd">
    <project>
        <title>Project 1</title>
        <description>This project was my first ever project where it includes PHP, JavaScript, and HTML/CSS, allowing seamless interaction between users.</description>
        <image>project1.jpg</image>
    </project>
    <project>
        <title>Project 2</title>
        <description>This project was my second project which includes Bootstrap.</description>
        <image>project2.jpg</image>
    </project>
    <project>
        <title>Project 3</title>
        <description>This is my third project where I have included XML.</description>
        <image>project3.jpg</image>
    </project>
</projects>
